# HW9 - Fine-tuning BERT!

> 任務: 以BERT為基礎，fine-tune 出一個可以判斷文章「是否為廣告」的模型（label "1" 為廣告、"0"為非廣告）

> 計分方式：
1. Preprocessing (20%)
2. Training and validating (30%)
3. Predicting (20%)
4. **有做兩組以上的嘗試** （10%)（需在Markdown寫出你嘗試的參數組合及結果）
5. 取Accuracy最高的結果：(Acc - 0.8)x100
   例如你最好的model正確率有0.88，那你就會再加上(0.88-0.8)x100=8分！

給定train_df和test_df兩份資料，其中train_df為4000筆未經前處理的資料，test_df為1000筆清理乾淨的資料。

In [ ]:
#train_df

text  label
0  V領設計能夠修飾臉型😍\n減齡泡泡袖洋裝😉\n👉https://lihi1.com/JDym...      1
1  【20210303】\n能勇敢追夢的人\n身上都閃著和煦的光芒\n也是好生羨慕！\n-\n敬...      0
2                             玉 耳環\n#耳環 #玉 #earrings      1
3  【美國瘋潮WWE Taiwan】\n不管是WWE Elite還是AEW Unrivaled系...      1
4  🌈\n尋晚的post 一po已經被秒殺好多件的Vintage sports windbrea...      1

In [ ]:
#test_df

text  label
4000                                     是黑暗的陽光少女吧伊達邵碼頭      0
4001  本週新品真的是馬不停蹄的一週春裝新品越來越多寶寶客人們都買不停身為女孩妳能有不漂亮的權利嗎讓...      1
4002                                      霧眉住家工作室預約台中霧眉      1
4003  中長版挺料西裝外套兩側口袋與微腰身設計真的很美奶杏色天空藍共色草帽女孩圖簡約圖也是時髦穿搭的...      1
4004  男生染髮焦糖棕色質感低調的焦糖色讓男生頭髮也能有不一樣的選擇喜歡記得按讚追蹤並儲存焦糖棕色霧...      1

In [ ]:
import pickle
import torch
from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
from transformers import BertTokenizer, BertForSequenceClassification
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np

from tabulate import tabulate
from tqdm import trange
import random

# Step 1: Preprocessing steps with BERT 

💪 pretrained model請使用"bert-base-chinese" & BertForSequenceClassification (設定如下所示）

💪 
前處理步驟

1. 加入special tokens:
  - [CLS]: 每個句子的開頭 (ID 101)
  - [SEP]: 每個句子的結尾 (ID 102)
2. 每個句子長度相等:
  - 設定maximum sequence length，最多可到 512 tokens
  - Padding([PAD]) ：不足max length的句子以 ID 0補滿
  - Truncated: 太長的句子就切到max length
3. Attention mask:
  - List of 0/1 indicating whether the model should consider the tokens or not when learning their contextual representation. (special tokens也是1，只有[PAD] tokens為 0）

使用``tokenizer.encode_plus``這個function，得到結果會包含:

- input_ids: list of token IDs.
- attention_mask: list of 0/1 indicating which tokens should be considered by the model (return_attention_mask = True).


In [ ]:
tokenizer = BertTokenizer.from_pretrained(
    "bert-base-chinese",
    do_lower_case = True
    )

In [ ]:
token_id

tensor([[ 101, 7526, 6257,  ...,    0,    0,    0],
        [ 101, 5543, 1235,  ..., 4692, 4638,  102],
        [ 101, 4373, 5455,  ...,    0,    0,    0],
        ...,
        [ 101, 3362, 4197,  ..., 2523, 1599,  102],
        [ 101, 6258, 2157,  ...,    0,    0,    0],
        [ 101, 3615, 4638,  ..., 7415, 2130,  102]])

In [ ]:
attention_masks

tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1]])

In [ ]:
labels = torch.tensor(labels)
labels

tensor([1, 0, 1,  ..., 0, 0, 0])

# Step 2: Training and validation

💪 可調整參數(可探索各種組合)
- Max length (在前處理的tokenizer.encode_plus那一步就會設定了）
- Batch size
- Learning rate (Adam)

- Number of epochs
- validation ratio (training跟validating的資料比例）


In [ ]:
val_ratio = 
batch_size =  
epoch = 
lr = 

# Indices of the train and validation splits stratified by labels
'''
shuffle: 對原始數據進行隨機抽樣，保證隨機性。
stratify: 想要達到分層隨機抽樣的目的。特別是在原始數據中樣本標籤分佈不均衡時非常有用，一些分類問題可能會在目標類的分佈中表現出很大的不平衡：例如，負樣本可能比正樣本多幾倍。在這種情況下，建議使用分層抽樣
'''

train_idx, val_idx = train_test_split(
    np.arange(len(labels)),
    test_size = 
    shuffle = 
    stratify = )

# Train and validation sets
train_set = TensorDataset()
val_set = TensorDataset()

# Prepare DataLoader
train_dataloader = DataLoader()
validation_dataloader = DataLoader()

In [ ]:
# Load the BertForSequenceClassification model
model = BertForSequenceClassification.from_pretrained(
    'bert-base-chinese',
    num_labels = 2,
    output_attentions = False,
    output_hidden_states = False,
)

# Recommended learning rates (Adam): 5e-5, 3e-5, 2e-5. See: https://arxiv.org/pdf/1810.04805.pdf
optimizer = torch.optim.AdamW( )

# Run on GPU
model.cuda()

Some weights of the model checkpoint at bert-base-chinese were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(21128, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12,

In [ ]:
# use GPU if available
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# training and validating



Epoch:  33%|███▎      | 1/3 [00:25<00:50, 25.23s/it]


	 - Train loss: 0.4099
	 - Validation Accuracy: 0.8688
	 - Validation Precision: 0.9139
	 - Validation Recall: 0.8013
	 - Validation Specificity: 0.9321



Epoch:  67%|██████▋   | 2/3 [00:50<00:25, 25.02s/it]


	 - Train loss: 0.2723
	 - Validation Accuracy: 0.8213
	 - Validation Precision: 0.7653
	 - Validation Recall: 0.8994
	 - Validation Specificity: 0.7407



Epoch: 100%|██████████| 3/3 [01:15<00:00, 25.03s/it]


	 - Train loss: 0.1778
	 - Validation Accuracy: 0.8588
	 - Validation Precision: 0.8458
	 - Validation Recall: 0.8580
	 - Validation Specificity: 0.8528



# Predicting

⭐ 記得使用test_df!

In [ ]:
# Testing data prediction
# We need Token IDs and Attention Mask for inference on the new sentence
# Apply the tokenizer


print(test_ids[0])
print(test_attention_mask[0])
print(test_lbl[0])

/usr/local/lib/python3.9/dist-packages/transformers/tokenization_utils_base.py:2354: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  warnings.warn(


tensor([ 101, 3221, 7946, 3266, 4638, 7382, 1045, 2208, 1957, 1416,  823, 6888,
        6939, 4826, 7531,  102,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])
tensor(0)


In [ ]:
test_dataset = TensorDataset(test_ids, test_attention_mask)
test_dataloader = DataLoader(
            test_dataset, # The validation samples.
            sampler = SequentialSampler(test_dataset), # Pull out batches sequentially.
            batch_size = batch_size # Evaluate with this batch size.
        )

In [ ]:
# Get model prediction output


<ipython-input-61-fad07656194b>:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['prediction'] = predictions


text  label  prediction
4000                                     是黑暗的陽光少女吧伊達邵碼頭      0           0
4001  本週新品真的是馬不停蹄的一週春裝新品越來越多寶寶客人們都買不停身為女孩妳能有不漂亮的權利嗎讓...      1           1
4002                                      霧眉住家工作室預約台中霧眉      1           1
4003  中長版挺料西裝外套兩側口袋與微腰身設計真的很美奶杏色天空藍共色草帽女孩圖簡約圖也是時髦穿搭的...      1           1
4004  男生染髮焦糖棕色質感低調的焦糖色讓男生頭髮也能有不一樣的選擇喜歡記得按讚追蹤並儲存焦糖棕色霧...      1           1

In [ ]:
# Calculate validation metrics
preds = test_df['prediction']
labels = test_df['label']

b_tp = sum([preds == labels and preds == 1 for preds, labels in zip(preds, labels)])
b_fp = sum([preds != labels and preds == 1 for preds, labels in zip(preds, labels)]) #false positive
b_tn = sum([preds == labels and preds == 0 for preds, labels in zip(preds, labels)]) #true negative
b_fn =  sum([preds != labels and preds == 0 for preds, labels in zip(preds, labels)])

'''
  Returns the following metrics:
    - accuracy    = (TP + TN) / N
    - precision   = TP / (TP + FP)
    - recall      = TP / (TP + FN)
    - specificity = TN / (TN + FP)
'''

test_accuracy = (b_tp + b_tn) / len(labels)
test_precision = b_tp / (b_tp + b_fp) if (b_tp + b_fp) > 0 else 'nan'
test_recall = b_tp / (b_tp + b_fn) if (b_tp + b_fn) > 0 else 'nan'
test_specificity = b_tn / (b_tn + b_fp) if (b_tn + b_fp) > 0 else 'nan'

print(f'test_accuracy: {test_accuracy}')
print(f'test_precision: {test_precision}')
print(f'test_recall: {test_recall}')
print(f'test_specificity: {test_specificity}')


test_accuracy: 0.863
test_precision: 0.8532289628180039
test_recall: 0.8755020080321285
test_specificity: 0.850597609561753
